import * as __ol from './node_modules/ol';
import * as __ol_array from './node_modules/ol/array';
import * as __ol_asserts from './node_modules/ol/asserts';
import * as __ol_centerconstraint from './node_modules/ol/centerconstraint';
import * as __ol_color from './node_modules/ol/color';
import * as __ol_colorlike from './node_modules/ol/colorlike';
import * as __ol_control from './node_modules/ol/control';
import * as __ol_control_util from './node_modules/ol/control/util';
import * as __ol_coordinate from './node_modules/ol/coordinate';
import * as __ol_css from './node_modules/ol/css';
import * as __ol_dom from './node_modules/ol/dom';
import * as __ol_easing from './node_modules/ol/easing';
import * as __ol_events from './node_modules/ol/events';
import * as __ol_events_condition from './node_modules/ol/events/condition';
import * as __ol_extent from './node_modules/ol/extent';
import * as __ol_featureloader from './node_modules/ol/featureloader';
import * as __ol_format from './node_modules/ol/format';
import * as __ol_format_filter from './node_modules/ol/format/filter';
import * as __ol_format_xsd from './node_modules/ol/format/xsd';
import * as __ol_functions from './node_modules/ol/functions';
import * as __ol_geom from './node_modules/ol/geom';
import * as __ol_geom_flat_area from './node_modules/ol/geom/flat/area';
import * as __ol_geom_flat_center from './node_modules/ol/geom/flat/center';
import * as __ol_geom_flat_closest from './node_modules/ol/geom/flat/closest';
import * as __ol_geom_flat_contains from './node_modules/ol/geom/flat/contains';
import * as __ol_geom_flat_deflate from './node_modules/ol/geom/flat/deflate';
import * as __ol_geom_flat_flip from './node_modules/ol/geom/flat/flip';
import * as __ol_geom_flat_geodesic from './node_modules/ol/geom/flat/geodesic';
import * as __ol_geom_flat_inflate from './node_modules/ol/geom/flat/inflate';
import * as __ol_geom_flat_interiorpoint from './node_modules/ol/geom/flat/interiorpoint';
import * as __ol_geom_flat_interpolate from './node_modules/ol/geom/flat/interpolate';
import * as __ol_geom_flat_intersectsextent from './node_modules/ol/geom/flat/intersectsextent';
import * as __ol_geom_flat_length from './node_modules/ol/geom/flat/length';
import * as __ol_geom_flat_orient from './node_modules/ol/geom/flat/orient';
import * as __ol_geom_flat_reverse from './node_modules/ol/geom/flat/reverse';
import * as __ol_geom_flat_segments from './node_modules/ol/geom/flat/segments';
import * as __ol_geom_flat_simplify from './node_modules/ol/geom/flat/simplify';
import * as __ol_geom_flat_straightchunk from './node_modules/ol/geom/flat/straightchunk';
import * as __ol_geom_flat_textpath from './node_modules/ol/geom/flat/textpath';
import * as __ol_geom_flat_topology from './node_modules/ol/geom/flat/topology';
import * as __ol_geom_flat_transform from './node_modules/ol/geom/flat/transform';
import * as __ol_has from './node_modules/ol/has';
import * as __ol_interaction from './node_modules/ol/interaction';
import * as __ol_layer from './node_modules/ol/layer';
import * as __ol_loadingstrategy from './node_modules/ol/loadingstrategy';
import * as __ol_math from './node_modules/ol/math';
import * as __ol_net from './node_modules/ol/net';
import * as __ol_obj from './node_modules/ol/obj';
import * as __ol_pixel from './node_modules/ol/pixel';
import * as __ol_proj from './node_modules/ol/proj';
import * as __ol_proj_epsg3857 from './node_modules/ol/proj/epsg3857';
import * as __ol_proj_epsg4326 from './node_modules/ol/proj/epsg4326';
import * as __ol_proj_proj4 from './node_modules/ol/proj/proj4';
import * as __ol_proj_projections from './node_modules/ol/proj/projections';
import * as __ol_proj_transforms from './node_modules/ol/proj/transforms';
import * as __ol_render from './node_modules/ol/render';
import * as __ol_render_canvas from './node_modules/ol/render/canvas';
import * as __ol_render_replay from './node_modules/ol/render/replay';
import * as __ol_render_webgl from './node_modules/ol/render/webgl';
import * as __ol_render_webgl_circlereplay_defaultshader from './node_modules/ol/render/webgl/circlereplay/defaultshader';
import * as __ol_render_webgl_linestringreplay_defaultshader from './node_modules/ol/render/webgl/linestringreplay/defaultshader';
import * as __ol_render_webgl_polygonreplay_defaultshader from './node_modules/ol/render/webgl/polygonreplay/defaultshader';
import * as __ol_render_webgl_texturereplay_defaultshader from './node_modules/ol/render/webgl/texturereplay/defaultshader';
import * as __ol_renderer_vector from './node_modules/ol/renderer/vector';
import * as __ol_renderer_webgl_defaultmapshader from './node_modules/ol/renderer/webgl/defaultmapshader';
import * as __ol_renderer_webgl_tilelayershader from './node_modules/ol/renderer/webgl/tilelayershader';
import * as __ol_reproj from './node_modules/ol/reproj';
import * as __ol_reproj_common from './node_modules/ol/reproj/common';
import * as __ol_resolutionconstraint from './node_modules/ol/resolutionconstraint';
import * as __ol_rotationconstraint from './node_modules/ol/rotationconstraint';
import * as __ol_size from './node_modules/ol/size';
import * as __ol_source from './node_modules/ol/source';
import * as __ol_source_common from './node_modules/ol/source/common';
import * as __ol_sphere from './node_modules/ol/sphere';
import * as __ol_string from './node_modules/ol/string';
import * as __ol_style from './node_modules/ol/style';
import * as __ol_tilecoord from './node_modules/ol/tilecoord';
import * as __ol_tilegrid from './node_modules/ol/tilegrid';
import * as __ol_tilegrid_common from './node_modules/ol/tilegrid/common';
import * as __ol_tileurlfunction from './node_modules/ol/tileurlfunction';
import * as __ol_transform from './node_modules/ol/transform';
import * as __ol_uri from './node_modules/ol/uri';
import * as __ol_util from './node_modules/ol/util';
import * as __ol_vec_mat4 from './node_modules/ol/vec/mat4';
import * as __ol_webgl from './node_modules/ol/webgl';
import * as __ol_xml from './node_modules/ol/xml';
import {default as MousePosition} from './node_modules/ol/control/MousePosition'

var ret = {};


ret.array = ret.array || {};
ret.asserts = ret.asserts || {};
ret.centerconstraint = ret.centerconstraint || {};
ret.color = ret.color || {};
ret.colorlike = ret.colorlike || {};
ret.control = ret.control || {};
ret.control = ret.control || {};
ret.control.util = ret.control.util || {};
ret.coordinate = ret.coordinate || {};
ret.css = ret.css || {};
ret.dom = ret.dom || {};
ret.easing = ret.easing || {};
ret.events = ret.events || {};
ret.events = ret.events || {};
ret.events.condition = ret.events.condition || {};
ret.extent = ret.extent || {};
ret.featureloader = ret.featureloader || {};
ret.format = ret.format || {};
ret.format = ret.format || {};
ret.format.filter = ret.format.filter || {};
ret.format = ret.format || {};
ret.format.xsd = ret.format.xsd || {};
ret.functions = ret.functions || {};
ret.geom = ret.geom || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.area = ret.geom.flat.area || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.center = ret.geom.flat.center || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.closest = ret.geom.flat.closest || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.contains = ret.geom.flat.contains || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.deflate = ret.geom.flat.deflate || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.flip = ret.geom.flat.flip || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.geodesic = ret.geom.flat.geodesic || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.inflate = ret.geom.flat.inflate || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.interiorpoint = ret.geom.flat.interiorpoint || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.interpolate = ret.geom.flat.interpolate || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.intersectsextent = ret.geom.flat.intersectsextent || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.length = ret.geom.flat.length || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.orient = ret.geom.flat.orient || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.reverse = ret.geom.flat.reverse || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.segments = ret.geom.flat.segments || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.simplify = ret.geom.flat.simplify || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.straightchunk = ret.geom.flat.straightchunk || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.textpath = ret.geom.flat.textpath || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.topology = ret.geom.flat.topology || {};
ret.geom = ret.geom || {};
ret.geom.flat = ret.geom.flat || {};
ret.geom.flat.transform = ret.geom.flat.transform || {};
ret.has = ret.has || {};
ret.interaction = ret.interaction || {};
ret.layer = ret.layer || {};
ret.loadingstrategy = ret.loadingstrategy || {};
ret.math = ret.math || {};
ret.net = ret.net || {};
ret.obj = ret.obj || {};
ret.pixel = ret.pixel || {};
ret.proj = ret.proj || {};
ret.proj = ret.proj || {};
ret.proj.epsg3857 = ret.proj.epsg3857 || {};
ret.proj = ret.proj || {};
ret.proj.epsg4326 = ret.proj.epsg4326 || {};
ret.proj = ret.proj || {};
ret.proj.proj4 = ret.proj.proj4 || {};
ret.proj = ret.proj || {};
ret.proj.projections = ret.proj.projections || {};
ret.proj = ret.proj || {};
ret.proj.transforms = ret.proj.transforms || {};
ret.render = ret.render || {};
ret.render = ret.render || {};
ret.render.canvas = ret.render.canvas || {};
ret.render = ret.render || {};
ret.render.replay = ret.render.replay || {};
ret.render = ret.render || {};
ret.render.webgl = ret.render.webgl || {};
ret.render = ret.render || {};
ret.render.webgl = ret.render.webgl || {};
ret.render.webgl.circlereplay = ret.render.webgl.circlereplay || {};
ret.render.webgl.circlereplay.defaultshader = ret.render.webgl.circlereplay.defaultshader || {};
ret.render = ret.render || {};
ret.render.webgl = ret.render.webgl || {};
ret.render.webgl.linestringreplay = ret.render.webgl.linestringreplay || {};
ret.render.webgl.linestringreplay.defaultshader = ret.render.webgl.linestringreplay.defaultshader || {};
ret.render = ret.render || {};
ret.render.webgl = ret.render.webgl || {};
ret.render.webgl.polygonreplay = ret.render.webgl.polygonreplay || {};
ret.render.webgl.polygonreplay.defaultshader = ret.render.webgl.polygonreplay.defaultshader || {};
ret.render = ret.render || {};
ret.render.webgl = ret.render.webgl || {};
ret.render.webgl.texturereplay = ret.render.webgl.texturereplay || {};
ret.render.webgl.texturereplay.defaultshader = ret.render.webgl.texturereplay.defaultshader || {};
ret.renderer = ret.renderer || {};
ret.renderer.vector = ret.renderer.vector || {};
ret.renderer = ret.renderer || {};
ret.renderer.webgl = ret.renderer.webgl || {};
ret.renderer.webgl.defaultmapshader = ret.renderer.webgl.defaultmapshader || {};
ret.renderer = ret.renderer || {};
ret.renderer.webgl = ret.renderer.webgl || {};
ret.renderer.webgl.tilelayershader = ret.renderer.webgl.tilelayershader || {};
ret.reproj = ret.reproj || {};
ret.reproj = ret.reproj || {};
ret.reproj.common = ret.reproj.common || {};
ret.resolutionconstraint = ret.resolutionconstraint || {};
ret.rotationconstraint = ret.rotationconstraint || {};
ret.size = ret.size || {};
ret.source = ret.source || {};
ret.source = ret.source || {};
ret.source.common = ret.source.common || {};
ret.sphere = ret.sphere || {};
ret.string = ret.string || {};
ret.style = ret.style || {};
ret.tilecoord = ret.tilecoord || {};
ret.tilegrid = ret.tilegrid || {};
ret.tilegrid = ret.tilegrid || {};
ret.tilegrid.common = ret.tilegrid.common || {};
ret.tileurlfunction = ret.tileurlfunction || {};
ret.transform = ret.transform || {};
ret.uri = ret.uri || {};
ret.util = ret.util || {};
ret.vec = ret.vec || {};
ret.vec.mat4 = ret.vec.mat4 || {};
ret.webgl = ret.webgl || {};
ret.xml = ret.xml || {}

Object.assign(ret, __ol);
Object.assign(ret.array, __ol_array);
Object.assign(ret.asserts, __ol_asserts);
Object.assign(ret.centerconstraint, __ol_centerconstraint);
Object.assign(ret.color, __ol_color);
Object.assign(ret.colorlike, __ol_colorlike);
Object.assign(ret.control, __ol_control);
Object.assign(ret.control.util, __ol_control_util);
Object.assign(ret.coordinate, __ol_coordinate);
Object.assign(ret.css, __ol_css);
Object.assign(ret.dom, __ol_dom);
Object.assign(ret.easing, __ol_easing);
Object.assign(ret.events, __ol_events);
Object.assign(ret.events.condition, __ol_events_condition);
Object.assign(ret.extent, __ol_extent);
Object.assign(ret.featureloader, __ol_featureloader);
Object.assign(ret.format, __ol_format);
Object.assign(ret.format.filter, __ol_format_filter);
Object.assign(ret.format.xsd, __ol_format_xsd);
Object.assign(ret.functions, __ol_functions);
Object.assign(ret.geom, __ol_geom);
Object.assign(ret.geom.flat.area, __ol_geom_flat_area);
Object.assign(ret.geom.flat.center, __ol_geom_flat_center);
Object.assign(ret.geom.flat.closest, __ol_geom_flat_closest);
Object.assign(ret.geom.flat.contains, __ol_geom_flat_contains);
Object.assign(ret.geom.flat.deflate, __ol_geom_flat_deflate);
Object.assign(ret.geom.flat.flip, __ol_geom_flat_flip);
Object.assign(ret.geom.flat.geodesic, __ol_geom_flat_geodesic);
Object.assign(ret.geom.flat.inflate, __ol_geom_flat_inflate);
Object.assign(ret.geom.flat.interiorpoint, __ol_geom_flat_interiorpoint);
Object.assign(ret.geom.flat.interpolate, __ol_geom_flat_interpolate);
Object.assign(ret.geom.flat.intersectsextent, __ol_geom_flat_intersectsextent);
Object.assign(ret.geom.flat.length, __ol_geom_flat_length);
Object.assign(ret.geom.flat.orient, __ol_geom_flat_orient);
Object.assign(ret.geom.flat.reverse, __ol_geom_flat_reverse);
Object.assign(ret.geom.flat.segments, __ol_geom_flat_segments);
Object.assign(ret.geom.flat.simplify, __ol_geom_flat_simplify);
Object.assign(ret.geom.flat.straightchunk, __ol_geom_flat_straightchunk);
Object.assign(ret.geom.flat.textpath, __ol_geom_flat_textpath);
Object.assign(ret.geom.flat.topology, __ol_geom_flat_topology);
Object.assign(ret.geom.flat.transform, __ol_geom_flat_transform);
Object.assign(ret.has, __ol_has);
Object.assign(ret.interaction, __ol_interaction);
Object.assign(ret.layer, __ol_layer);
Object.assign(ret.loadingstrategy, __ol_loadingstrategy);
Object.assign(ret.math, __ol_math);
Object.assign(ret.net, __ol_net);
Object.assign(ret.obj, __ol_obj);
Object.assign(ret.pixel, __ol_pixel);
Object.assign(ret.proj, __ol_proj);
Object.assign(ret.proj.epsg3857, __ol_proj_epsg3857);
Object.assign(ret.proj.epsg4326, __ol_proj_epsg4326);
Object.assign(ret.proj.proj4, __ol_proj_proj4);
Object.assign(ret.proj.projections, __ol_proj_projections);
Object.assign(ret.proj.transforms, __ol_proj_transforms);
Object.assign(ret.render, __ol_render);
Object.assign(ret.render.canvas, __ol_render_canvas);
Object.assign(ret.render.replay, __ol_render_replay);
Object.assign(ret.render.webgl, __ol_render_webgl);
Object.assign(ret.render.webgl.circlereplay.defaultshader, __ol_render_webgl_circlereplay_defaultshader);
Object.assign(ret.render.webgl.linestringreplay.defaultshader, __ol_render_webgl_linestringreplay_defaultshader);
Object.assign(ret.render.webgl.polygonreplay.defaultshader, __ol_render_webgl_polygonreplay_defaultshader);
Object.assign(ret.render.webgl.texturereplay.defaultshader, __ol_render_webgl_texturereplay_defaultshader);
Object.assign(ret.renderer.vector, __ol_renderer_vector);
Object.assign(ret.renderer.webgl.defaultmapshader, __ol_renderer_webgl_defaultmapshader);
Object.assign(ret.renderer.webgl.tilelayershader, __ol_renderer_webgl_tilelayershader);
Object.assign(ret.reproj, __ol_reproj);
Object.assign(ret.reproj.common, __ol_reproj_common);
Object.assign(ret.resolutionconstraint, __ol_resolutionconstraint);
Object.assign(ret.rotationconstraint, __ol_rotationconstraint);
Object.assign(ret.size, __ol_size);
Object.assign(ret.source, __ol_source);
Object.assign(ret.source.common, __ol_source_common);
Object.assign(ret.sphere, __ol_sphere);
Object.assign(ret.string, __ol_string);
Object.assign(ret.style, __ol_style);
Object.assign(ret.tilecoord, __ol_tilecoord);
Object.assign(ret.tilegrid, __ol_tilegrid);
Object.assign(ret.tilegrid.common, __ol_tilegrid_common);
Object.assign(ret.tileurlfunction, __ol_tileurlfunction);
Object.assign(ret.transform, __ol_transform);
Object.assign(ret.uri, __ol_uri);
Object.assign(ret.util, __ol_util);
Object.assign(ret.vec.mat4, __ol_vec_mat4);
Object.assign(ret.webgl, __ol_webgl);
Object.assign(ret.xml, __ol_xml);
ret.control.MousePosition = MousePosition

export default ret;
